name: Test and Deploy

on:
  push:
    branches:
      - main

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo 'Hello from the pipeline!'

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout and clone repo
        uses: actions/checkout@v2

      - name: Install Depenedencies
        run: npm install

      - name: Setup PSQL
        uses: harmon758/postgresql-action@v1
        with:
          postgresql db: test_db
          postgresql user: mr_tester
          postgresql password: p4ssw0rd

      - name: Test Utils and App
        run: PGDATABASE=test_db PGUSER=mr_tester PGPASSWORD=p4ssw0rd npm test

  deploy:
    runs-on: ubuntu-latest
    needs: test
    uses: akhileshns/heroku-deploy@v3.12.12
    with:
      heroku_api_key: ${{secrets.HEROKU_API_KEY}}
      heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
      heroku_email: ${{secrets.HEROKU_EMAIL}}
